name: Deploy Vue storybook to IBM Cloud and GitHub Pages

on:
  workflow_dispatch:
  # push:
  #   tags:
  #     # Matches tags that have the shape `vX.Y.Z`. Reference:
  #     # https://help.github.com/en/articles/workflow-syntax-for-github-actions#onpushpull_requesttagsbranches
  #     - 'v[0-9]+.[0-9]+.[0-9]+'
  #     # Ignore tags that use a preid after `vX.Y.Z`, for example: vX.Y.Z-alpha.0
  #     # https://help.github.com/en/articles/workflow-syntax-for-github-actions#example-using-positive-and-negative-patterns
  #     - '!v[0-9]+.[0-9]+.[0-9]+-*'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies from our offline mirror
        run: yarn install --offline
      - name: Install ibmcloud CLI
        run: curl -fsSL https://clis.cloud.ibm.com/install/osx | sh
      - name: Login to IBM Cloud
        env:
          CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY}}
        run: |
          ibmcloud login \
            -a 'https://cloud.ibm.com' \
            --apikey "$CLOUD_API_KEY" \
            -r 'us-south'
          ibmcloud target -o 'carbon-design-system' -s 'production'
      - name: Install IBM Cloud plugins
        run: |
          ibmcloud cf install
          ibmcloud cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          ibmcloud cf install-plugin blue-green-deploy -f -r CF-Community
      - name: Deploy Vue storybook
        run: |
          yarn build:storybook --quiet
          ibmcloud cf blue-green-deploy carbon-storybook-vue \
            -f storybook/manifest.yml \
            --delete-old-apps
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'storybook/storybook-static'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
